config/routes.rb
Rails.application.routes.draw do

  # resources :payments

  resources :payment_plans do
    member do
      get 'select'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :rewards

  resources :redemptions

  resources :offer_shares

  resources :advocates

  resources :payments
  get 'payments/test', to: 'payments#test'

  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')

  resources :customers

  resources :offers do
    member do
      get 'publish'
    end
  end

  end

app/models/advocate.rb
class Advocate < ActiveRecord::Base
  has_many :offer_shares

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :offers
  has_one :user
  belongs_to :payment_plans
  has_many :payments

  def create_stripe_customer stripe_token
    stripe_customer = Stripe::Customer.create(
      :description => "OfferShareNetwork Customer",
      :card => stripe_token,
      :plan => "monthly"
    )
    stripe_customer_hash = JSON.parse(stripe_customer.to_s)
    raise stripe_customer_hash.to_yaml
    self.stripe_customer_id = 0
    self.save
  end

  def get_stripe_customer
    Stripe::Customer.retrieve self.stripe_customer_id
  end

  def paid?
    self.active == true ? true : false
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :customer
  has_many :offer_shares

  def offer_redemption_count
    redemptions = 0
    self.offer_shares.each do |offer_share|
      redemptions += offer_share.redemptions.count
    end

    return redemptions
  end

  def published?
    self.published.nil? == false ? true : false
  end

  def publish!
    self.publish = DateTime.now
    self.save
  end

end

app/models/offer_share.rb
class OfferShare < ActiveRecord::Base
  belongs_to :offer
  belongs_to :advocate
  has_many :redemptions

  validates :code, uniqueness: true

  before_create :create_code

  protected
    def create_code
      self.code = ('a'..'z').to_a.shuffle[0,3].join + '-' + ('a'..'z').to_a.shuffle[0,3].join
      # probably not a long term solution
      self.create_code unless self.valid?
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :customer
  belongs_to :payment_plan
end

app/models/payment_plan.rb
class PaymentPlan < ActiveRecord::Base
  has_many :customers
  has_many :payments
end

app/models/redemption.rb
class Redemption < ActiveRecord::Base
  belongs_to :offer_share
  validates :offer_share, presence: true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :offer_share
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :customer
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :validate_customer

  def index
    @customer = current_user.customer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/advocates_helper.rb
module AdvocatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/offer_shares_helper.rb
module OfferSharesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/redemptions_helper.rb
module RedemptionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/dashboard/index.html.erb
<% content_for :header, "Dashboard" %>

<% if current_user.customer.offers.count == 0 %>
<h3>You don't have any offers yet.
<small><%= link_to('Create first offer now', new_offer_path)  %></small>
<% end %>

<% if @customer.offers.count > 0 %>
<h3 class="page-header">Offers</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Offer</th>
      <th>Advocates</th>
      <th>Redemptions</th>
      <th>Published?</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @customer.offers.each do |offer| %>
    <tr>
      <td><%= offer.name %></td>
      <td><%= offer.offer_shares.count %></td>
      <td><%= offer.offer_redemption_count %></td>
      <% status_icon = offer.published? ? 'glyphicon-ok text-success' : 'glyphicon-remove text-danger' %>
      <td><span class="glyphicon <%= status_icon  %>"></span></td>
      <td><%= link_to("edit", edit_offer_path(offer)) %>
      <td><%= link_to("view", offer_path(offer)) %>
      <td>
        <% if offer.published.nil? %>
          <%= link_to("publish", publish_offer_path(offer)) %>
        <% end %>
        <% if !offer.published.nil? && Date.new < offer.expires %>
          <%= link_to("stop", offer_path(offer)) %>
        <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>