config/routes.rb
Rails.application.routes.draw do

  # resources :payments

  resources :payment_plans do
    member do
      get 'select'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :rewards

  resources :redemptions

  resources :offer_shares

  resources :advocates

  resources :payments
  get 'payments/test', to: 'payments#test'

  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')

  resources :customers

  resources :offers do
    member do
      get 'publish'
    end
  end

  end

app/models/advocate.rb
class Advocate < ActiveRecord::Base
  has_many :offer_shares

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :offers
  has_one :user
  belongs_to :payment_plans
  has_many :payments

  def create_stripe_customer stripe_token
    stripe_customer = Stripe::Customer.create(
      :description => "OfferShareNetwork Customer",
      :card => stripe_token,
      :plan => "monthly"
    )
    stripe_customer_hash = JSON.parse(stripe_customer.to_s)
    raise stripe_customer_hash.to_yaml
    self.stripe_customer_id = 0
    self.save
  end

  def get_stripe_customer
    Stripe::Customer.retrieve self.stripe_customer_id
  end

  def paid?
    self.active == true ? true : false
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :customer
  has_many :offer_shares

  def offer_redemption_count
    redemptions = 0
    self.offer_shares.each do |offer_share|
      redemptions += offer_share.redemptions.count
    end

    return redemptions
  end

  def published?
    self.published.nil? == false ? true : false
  end

  def publish!
    self.publish = DateTime.now
    self.save
  end

end

app/models/offer_share.rb
class OfferShare < ActiveRecord::Base
  belongs_to :offer
  belongs_to :advocate
  has_many :redemptions

  validates :code, uniqueness: true

  before_create :create_code

  protected
    def create_code
      self.code = ('a'..'z').to_a.shuffle[0,3].join + '-' + ('a'..'z').to_a.shuffle[0,3].join
      # probably not a long term solution
      self.create_code unless self.valid?
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :customer
  belongs_to :payment_plan
end

app/models/payment_plan.rb
class PaymentPlan < ActiveRecord::Base
  has_many :customers
  has_many :payments
end

app/models/redemption.rb
class Redemption < ActiveRecord::Base
  belongs_to :offer_share
  validates :offer_share, presence: true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :offer_share
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :customer
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_filter :validate_customer

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.where(customer: current_user.customer)
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.customer_id = current_user.customer_id
    redirect_to @offer, notice: 'Offer was successfully created.'
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      redirect_to offers_url, notice: 'Offer was successfully destroyed.'
    end
  end

  def publish
    # check to see if customer is paid
    @offer = Offer.find(params[:id])

    if current_user.customer.paid?
      @offer.publish!
      redirect_to @offer, notice: 'Offer was successfully published.'
    else
      redirect_to @offer, notice: 'Offer not published. Please update payment information to publish your offer.'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:name, :description, :reward_description, :reward_factor, :redemption_value, :active, :image_url, :published, :expires)
    end
end

app/helpers/advocates_helper.rb
module AdvocatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/offer_shares_helper.rb
module OfferSharesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/payment_plans_helper.rb
module PaymentPlansHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/redemptions_helper.rb
module RedemptionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :reward_description %><br>
    <%= f.text_field :reward_description %>
  </div>
  <div class="field">
    <%= f.label :reward_factor %><br>
    <%= f.text_field :reward_factor %>
  </div>
  <div class="field">
    <%= f.label :redemption_value %><br>
    <%= f.text_field :redemption_value %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Name</th>
      <th>Description</th>
      <th>Reward description</th>
      <th>Reward factor</th>
      <th>Redemption value</th>
      <th>Image url</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.customer.name %></td>
        <td><%= offer.name %></td>
        <td><%= offer.description %></td>
        <td><%= offer.reward_description %></td>
        <td><%= offer.reward_factor %></td>
        <td><%= offer.redemption_value %></td>
        <td><%= offer.image_url %></td>
        <td><%= offer.published %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Publish', publish_offer_path(offer) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<% content_for :header, "New offer for #{current_user.customer.name}" %>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p>
  <strong>Customer:</strong>
  <%= @offer.customer.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @offer.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>

<p>
  <strong>Reward description:</strong>
  <%= @offer.reward_description %>
</p>

<p>
  <strong>Reward factor:</strong>
  <%= @offer.reward_factor %>
</p>

<p>
  <strong>Redemption value:</strong>
  <%= @offer.redemption_value %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @offer.image_url %>
</p>

<% if @offer.published? %>
<p>
  <strong>Published:</strong>
  <%= @offer.published %>
</p>
<% end %>
<table>
  <thead>
    <tr>
      <td>Advocate</td>
      <td>Redemptions</td>
      <td>Projected ROI</td>
    </tr>
  </thead>
  <tbody>
    <% @offer.offer_shares.each do |offer_share| %>
    <tr>
      <td><%= offer_share.advocate.email %></td>
      <td><%= offer_share.redemptions.count %></td>
      <td><%= offer_share.redemptions.count * @offer.redemption_value.to_i %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Create Offer Share', new_offer_share_path(@offer, current_user) %>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>