config/routes.rb
Rails.application.routes.draw do

  # resources :payments

  resources :payment_plans do
    member do
      get 'select'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :rewards

  resources :redemptions

  resources :offer_shares

  resources :advocates

  resources :payments
  get 'payments/test', to: 'payments#test'

  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')

  resources :customers

  resources :offers do
    member do
      get 'publish'
    end
  end

  end

app/models/advocate.rb
class Advocate < ActiveRecord::Base
  has_many :offer_shares

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :offers
  has_one :user
  belongs_to :payment_plans
  has_many :payments

  def create_stripe_customer stripe_token
    stripe_customer = Stripe::Customer.create(
      :description => "OfferShareNetwork Customer",
      :card => stripe_token,
      :plan => "monthly"
    )
    stripe_customer_hash = JSON.parse(stripe_customer.to_s)
    raise stripe_customer_hash.to_yaml
    self.stripe_customer_id = 0
    self.save
  end

  def get_stripe_customer
    Stripe::Customer.retrieve self.stripe_customer_id
  end

  def paid?
    self.active == true ? true : false
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :customer
  has_many :offer_shares

  def offer_redemption_count
    redemptions = 0
    self.offer_shares.each do |offer_share|
      redemptions += offer_share.redemptions.count
    end

    return redemptions
  end

  def published?
    self.published.nil? == false ? true : false
  end

  def publish!
    self.publish = DateTime.now
    self.save
  end

end

app/models/offer_share.rb
class OfferShare < ActiveRecord::Base
  belongs_to :offer
  belongs_to :advocate
  has_many :redemptions

  validates :code, uniqueness: true

  before_create :create_code

  protected
    def create_code
      self.code = ('a'..'z').to_a.shuffle[0,3].join + '-' + ('a'..'z').to_a.shuffle[0,3].join
      # probably not a long term solution
      self.create_code unless self.valid?
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :customer
  belongs_to :payment_plan
end

app/models/payment_plan.rb
class PaymentPlan < ActiveRecord::Base
  has_many :customers
  has_many :payments
end

app/models/redemption.rb
class Redemption < ActiveRecord::Base
  belongs_to :offer_share
  validates :offer_share, presence: true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :offer_share
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :customer
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payment_plans_controller.rb
class PaymentPlansController < ApplicationController
  before_action :set_payment_plan, only: [:show, :edit, :update, :destroy]

  # GET /payment_plans
  # GET /payment_plans.json
  def index
    @payment_plans = PaymentPlan.all
  end

  # GET /payment_plans/1
  # GET /payment_plans/1.json
  def show
  end

  # GET /payment_plans/new
  def new
    @payment_plan = PaymentPlan.new
  end

  # GET /payment_plans/1/edit
  def edit
  end

  # POST /payment_plans
  # POST /payment_plans.json
  def create
    @payment_plan = PaymentPlan.new(payment_plan_params)

    respond_to do |format|
      if @payment_plan.save
        redirect_to @payment_plan, notice: 'Payment plan was successfully created.'
      else
        render :new
      end
    end
  end

  def select
    @payment_plan = PaymentPlan.find(params[:id])
    current_user.customer.payment_plan_id = @payment_plan
    redirect_to payments_path, notice: 'Payment plan was successfully updated. Please enter payment information'
  end

  # PATCH/PUT /payment_plans/1
  # PATCH/PUT /payment_plans/1.json
  def update
    respond_to do |format|
      if @payment_plan.update(payment_plan_params)
        redirect_to @payment_plan, notice: 'Payment plan was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /payment_plans/1
  # DELETE /payment_plans/1.json
  def destroy
    @payment_plan.destroy
    respond_to do |format|
      redirect_to payment_plans_url, notice: 'Payment plan was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_plan
      @payment_plan = PaymentPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_plan_params
      params.require(:payment_plan).permit(:name, :description, :amount, :billing_period, :stripe_id)
    end
end

app/helpers/advocates_helper.rb
module AdvocatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/offer_shares_helper.rb
module OfferSharesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/payment_plans_helper.rb
module PaymentPlansHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/redemptions_helper.rb
module RedemptionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/payment_plans/_form.html.erb
<%= form_for(@payment_plan) do |f| %>
  <% if @payment_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_plan.errors.count, "error") %> prohibited this payment_plan from being saved:</h2>

      <ul>
      <% @payment_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :billing_period %><br>
    <%= f.text_field :billing_period %>
  </div>
  <div class="field">
    <%= f.label :stripe_id %><br>
    <%= f.text_field :stripe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_plans/edit.html.erb
<h1>Editing payment_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_plan %> |
<%= link_to 'Back', payment_plans_path %>

app/views/payment_plans/index.html.erb
<h1>Listing payment_plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Billing period</th>
      <th>Stripe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_plans.each do |payment_plan| %>
      <tr>
        <td><%= payment_plan.name %></td>
        <td><%= payment_plan.description %></td>
        <td><%= payment_plan.amount %></td>
        <td><%= payment_plan.billing_period %></td>
        <td><%= payment_plan.stripe_id %></td>
        <td><%= link_to 'Show', payment_plan %></td>
        <td><%= link_to 'Edit', edit_payment_plan_path(payment_plan) %></td>
        <td><%= link_to 'Destroy', payment_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment plan', new_payment_plan_path %>

app/views/payment_plans/new.html.erb
<h1>New payment_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_plans_path %>

app/views/payment_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payment_plan.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @payment_plan.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment_plan.amount %>
</p>

<p>
  <strong>Billing period:</strong>
  <%= @payment_plan.billing_period %>
</p>

<p>
  <strong>Stripe:</strong>
  <%= @payment_plan.stripe_id %>
</p>

<%= link_to 'Edit', edit_payment_plan_path(@payment_plan) %> |
<%= link_to 'Back', payment_plans_path %>