config/routes.rb
Rails.application.routes.draw do

  # resources :payments

  resources :payment_plans do
    member do
      get 'select'
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :rewards

  resources :redemptions

  resources :offer_shares

  resources :advocates

  resources :payments
  get 'payments/test', to: 'payments#test'

  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')

  resources :customers

  resources :offers do
    member do
      get 'publish'
    end
  end

  end

app/models/advocate.rb
class Advocate < ActiveRecord::Base
  has_many :offer_shares

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :offers
  has_one :user
  belongs_to :payment_plans
  has_many :payments

  def create_stripe_customer stripe_token
    stripe_customer = Stripe::Customer.create(
      :description => "OfferShareNetwork Customer",
      :card => stripe_token,
      :plan => "monthly"
    )
    stripe_customer_hash = JSON.parse(stripe_customer.to_s)
    raise stripe_customer_hash.to_yaml
    self.stripe_customer_id = 0
    self.save
  end

  def get_stripe_customer
    Stripe::Customer.retrieve self.stripe_customer_id
  end

  def paid?
    self.active == true ? true : false
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :customer
  has_many :offer_shares

  def offer_redemption_count
    redemptions = 0
    self.offer_shares.each do |offer_share|
      redemptions += offer_share.redemptions.count
    end

    return redemptions
  end

  def published?
    self.published.nil? == false ? true : false
  end

  def publish!
    self.publish = DateTime.now
    self.save
  end

end

app/models/offer_share.rb
class OfferShare < ActiveRecord::Base
  belongs_to :offer
  belongs_to :advocate
  has_many :redemptions

  validates :code, uniqueness: true

  before_create :create_code

  protected
    def create_code
      self.code = ('a'..'z').to_a.shuffle[0,3].join + '-' + ('a'..'z').to_a.shuffle[0,3].join
      # probably not a long term solution
      self.create_code unless self.valid?
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :customer
  belongs_to :payment_plan
end

app/models/payment_plan.rb
class PaymentPlan < ActiveRecord::Base
  has_many :customers
  has_many :payments
end

app/models/redemption.rb
class Redemption < ActiveRecord::Base
  belongs_to :offer_share
  validates :offer_share, presence: true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :offer_share
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :customer
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/advocates_helper.rb
module AdvocatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/redemptions_helper.rb
module RedemptionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OfferShareNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Offer Share Network</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <!-- <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form> -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/">Dashboard</a></li>
            <!-- <li><%= link_to 'Customers', customers_path %></li> -->
            <li><%= link_to 'Offers', offers_path %></li>
            <li><%= link_to 'Advocates', advocates_path %></li>
            <li><%= link_to 'OfferShares', offer_shares_path %></li>
            <li><%= link_to 'Redemptions', redemptions_path %></li>
            <li><%= link_to 'Rewards', rewards_path %></li>
            <li><%= link_to 'Payment Plans', payment_plans_path %></li>
            <%= render 'devise/menu/registration_items' %>
            <%= render 'devise/menu/login_items' %>
          </ul>
        </div>


        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <% if notice || alert %>
        <div class="alert alert-info">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <% end %>
        <h1 class="page-header"><%= yield(:header) %></h1>

        <%= yield %>

      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OfferShareNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

    <div class="container">

      <!-- <form class="form-signin" role="form">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="email" class="form-control" placeholder="Email address" required autofocus>
        <input type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form> -->

    <%= yield %>

    </div> <!-- /container -->

  </body>
</html>